---
title: "Write the title of the lab here"
author: "Your Name"
date: "Date of lab session"
output:
  html_document:
    highlight: pygments
    theme: spacelab
  pdf_document: default
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# Remember that you only need to install R packages once in R
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(ggplot2)
```

* * *

## Lab report

**Load data here**
```{r}
# Enter your code for loading the data here

```

#### Question 1: 

[Enter your response for Question 1 here.]

```{r}
# Enter your code for question 1 here

```

#### Question 2:

[Enter your response for Question 2 here.]

```{r}
# Enter your code for question 2 here
```


#### Question 3:

[Enter your response for Question 3 here.]

```{r}
# Enter your code for question 3 here
```


#### Question 4:

[Enter your response for Question 4 here.]

```{r}
# Enter your code for question 4 here
```


#### Question 5:

[Enter your response for Question 5 here.]

```{r}
# Enter your code for question 5 here
```


#### Question 6:

[Enter your response for Question 6 here.]

```{r}
# Enter your code for question 6 here
```


* * *



